package algorithms

import (
	"fmt"
	"github.com/stretchr/testify/assert"
	"testing"
)

// testcases
var tcs = []struct {
	str1 string
	str2 string
	ans  string
}{

	{
		"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
		"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
		"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	},

	{
		"AAAABBB",
		"AAAAAAAAAAB",
		"",
	},

	{
		"AAAAAAA",
		"AAAAAAAAAAA",
		"A",
	},

	{
		"NLZGMNLZGMNLZGMNLZGMNLZGMNLZGMNLZGMNLZGM",
		"NLZGMNLZGMNLZGMNLZGMNLZGMNLZGMNLZGMNLZGMNLZGM",
		"NLZGM",
	},

	{
		"ABCABC",
		"ABC",
		"ABC",
	},

	{
		"ABABAB",
		"ABAB",
		"AB",
	},

	{
		"LEET",
		"CODE",
		"",
	},
}

func Test_gcdOfStrings(t *testing.T) {
	ast := assert.New(t)

	fmt.Printf("------------------------Leetcode Problem 1071. Greatest Common Divisor of Strings------------------------\n")

	for _, tc := range tcs {
		fmt.Printf("【Input】: str1 = %v, str2 = %v\n【Output】: %v\n", tc.str1, tc.str2, gcdOfStrings(tc.str1, tc.str2))
		ast.Equal(tc.ans, gcdOfStrings(tc.str1, tc.str2), "Case: %v", tc)
	}
	fmt.Printf("\n\n\n")
}

func Benchmark_gcdOfStrings(b *testing.B) {
	for i := 0; i < b.N; i++ {
		for _, tc := range tcs {
			gcdOfStrings(tc.str1, tc.str2)
		}
	}
}
