--
-- @lc app=leetcode id=1757 lang=postgresql
--
-- [1757] Recyclable and Low Fat Products
--
-- https://leetcode.com/problems/recyclable-and-low-fat-products/description/
--
-- database
-- Easy (89.39%)
-- Likes:    2649
-- Dislikes: 119
-- Total Accepted:    1.6M
-- Total Submissions: 1.8M
-- Testcase Example:  '{"headers":{"Products":["product_id","low_fats","recyclable"]},"rows":{"Products":[["0","Y","N"],["1","Y","Y"],["2","N","Y"],["3","Y","Y"],["4","N","N"]]}}'
--
-- Table: Products
-- 
-- 
-- +-------------+---------+
-- | Column Name | Type    |
-- +-------------+---------+
-- | product_id  | int     |
-- | low_fats    | enum    |
-- | recyclable  | enum    |
-- +-------------+---------+
-- product_id is the primary key (column with unique values) for this table.
-- low_fats is an ENUM (category) of type ('Y', 'N') where 'Y' means this
-- product is low fat and 'N' means it is not.
-- recyclable is an ENUM (category) of types ('Y', 'N') where 'Y' means this
-- product is recyclable and 'N' means it is not.
-- 
-- 
-- 
-- Write a solution to find the ids of products that are both low fat and
-- recyclable.
-- 
-- Return the result table in any order.
-- 
-- The result format is in the following example.
-- 
-- 
-- Example 1:
-- 
-- 
-- Input: 
-- Products table:
-- +-------------+----------+------------+
-- | product_id  | low_fats | recyclable |
-- +-------------+----------+------------+
-- | 0           | Y        | N          |
-- | 1           | Y        | Y          |
-- | 2           | N        | Y          |
-- | 3           | Y        | Y          |
-- | 4           | N        | N          |
-- +-------------+----------+------------+
-- Output: 
-- +-------------+
-- | product_id  |
-- +-------------+
-- | 1           |
-- | 3           |
-- +-------------+
-- Explanation: Only products 1 and 3 are both low fat and recyclable.
-- 
-- 
--

-- @lc code=start
-- Write your PostgreSQL query statement below
select product_id
from Products
where low_fats = 'Y' and recyclable = 'Y'

-- @lc code=end

