--
-- @lc app=leetcode id=196 lang=postgresql
--
-- [196] Delete Duplicate Emails
--
-- https://leetcode.com/problems/delete-duplicate-emails/description/
--
-- database
-- Easy (63.55%)
-- Likes:    1726
-- Dislikes: 360
-- Total Accepted:    647.7K
-- Total Submissions: 1M
-- Testcase Example:  '{"headers": {"Person": ["id", "email"]}, "rows": {"Person": [[1, "john@example.com"], [2, "bob@example.com"], [3, "john@example.com"]]}}'
--
-- Table: Person
-- 
-- 
-- +-------------+---------+
-- | Column Name | Type    |
-- +-------------+---------+
-- | id          | int     |
-- | email       | varchar |
-- +-------------+---------+
-- id is the primary key (column with unique values) for this table.
-- Each row of this table contains an email. The emails will not contain
-- uppercase letters.
-- 
-- 
-- 
-- 
-- Write a solution to delete all duplicate emails, keeping only one unique
-- email with the smallest id.
-- 
-- For SQL users, please note that you are supposed to write a DELETE statement
-- and not a SELECT one.
-- 
-- For Pandas users, please note that you are supposed to modify Person in
-- place.
-- 
-- After running your script, the answer shown is the Person table. The driver
-- will first compile and run your piece of code and then show the Person
-- table. The final order of the Person table does not matter.
-- 
-- The result format is in the following example.
-- 
-- 
-- Example 1:
-- 
-- 
-- Input: 
-- Person table:
-- +----+------------------+
-- | id | email            |
-- +----+------------------+
-- | 1  | john@example.com |
-- | 2  | bob@example.com  |
-- | 3  | john@example.com |
-- +----+------------------+
-- Output: 
-- +----+------------------+
-- | id | email            |
-- +----+------------------+
-- | 1  | john@example.com |
-- | 2  | bob@example.com  |
-- +----+------------------+
-- Explanation: john@example.com is repeated two times. We keep the row with
-- the smallest Id = 1.
-- 
-- 
--

-- @lc code=start
-- Write your PostgreSQL query statement below
delete from Person p
using Person p2
where p.Email = p2.Email
and p.Id > p2.Id

-- @lc code=end

