--
-- @lc app=leetcode id=182 lang=postgresql
--
-- [182] Duplicate Emails
--
-- https://leetcode.com/problems/duplicate-emails/description/
--
-- database
-- Easy (71.90%)
-- Likes:    2159
-- Dislikes: 74
-- Total Accepted:    774.5K
-- Total Submissions: 1.1M
-- Testcase Example:  '{"headers": {"Person": ["id", "email"]}, "rows": {"Person": [[1, "a@b.com"], [2, "c@d.com"], [3, "a@b.com"]]}}'
--
-- Table: Person
-- 
-- 
-- +-------------+---------+
-- | Column Name | Type    |
-- +-------------+---------+
-- | id          | int     |
-- | email       | varchar |
-- +-------------+---------+
-- id is the primary key (column with unique values) for this table.
-- Each row of this table contains an email. The emails will not contain
-- uppercase letters.
-- 
-- 
-- 
-- 
-- Write a solution to report all the duplicate emails. Note that it's
-- guaranteed that the email field is not NULL.
-- 
-- Return the result table in any order.
-- 
-- The result format is in the following example.
-- 
-- 
-- Example 1:
-- 
-- 
-- Input: 
-- Person table:
-- +----+---------+
-- | id | email   |
-- +----+---------+
-- | 1  | a@b.com |
-- | 2  | c@d.com |
-- | 3  | a@b.com |
-- +----+---------+
-- Output: 
-- +---------+
-- | Email   |
-- +---------+
-- | a@b.com |
-- +---------+
-- Explanation: a@b.com is repeated two times.
-- 
-- 
--

-- @lc code=start
-- Write your PostgreSQL query statement below
select email
from Person
group by email
having count(email) > 1

-- @lc code=end

